spring:
  application:
    name: backend

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5433/insight_db
    username: insight_user
    password: password